import { Form, useLoaderData, useOutletContext } from "react-router-dom";
import { useStateUpdater } from "../../common/helpers";
import { RootState } from "../root/Root";
import style from "./Callback.module.css";

export interface CallbackParams {
  code: string;
  clientId: string;
  redirectUri?: string;
}

export interface TokenRequestConfiguration {
  tokenEndpoint: string;
  clientSecret: string;
  useProxy: boolean;
  proxyUrl?: string;
  useBodyCredentials: boolean;
}

export interface CallbackData {
  params: CallbackParams;
  config: TokenRequestConfiguration;
}

export const STATE_KEY = "callbackState";

export default function Callback() {
  const context = useOutletContext() as RootState;
  const data = useLoaderData() as CallbackData;

  const [config, handleConfigChange] = useStateUpdater(
    context,
    STATE_KEY,
    data.config
  );

  return (
    <article>
      <h3>Token Request</h3>
      <Form method="post" action="/token">
        <div className="grid">
          <label>
            <span
              className="unmarked-tooltip"
              data-tooltip="This is usually provided in documentation."
            >
              Token URL
            </span>
            <input
              required
              name="tokenUrl"
              type="url"
              value={config.tokenEndpoint}
              onChange={(event) =>
                handleConfigChange("tokenEndpoint", event.target.value)
              }
              placeholder="https://example.com/token"
            />
          </label>
          <label>
            <span
              className="unmarked-tooltip"
              data-tooltip="Generated by the server. Must be kept secure."
            >
              Client Secret
            </span>
            <input
              required
              name="clientSecret"
              type="password"
              value={config.clientSecret}
              onChange={(event) =>
                handleConfigChange("clientSecret", event.target.value)
              }
            />
          </label>
        </div>
        <div className="grid">
          <fieldset>
            <legend>Options</legend>
            <label id={style.useProxyLabel}>
              <input
                name="useProxy"
                type="checkbox"
                checked={config.useProxy}
                onChange={(event) =>
                  handleConfigChange("useProxy", event.target.checked)
                }
              />
              <span
                className="unmarked-tooltip"
                data-tooltip="Route the token request through a proxy server. You must trust this server."
                data-placement="right"
              >
                Use proxy
              </span>
            </label>
            {config.useProxy && (
              <>
                <h6 className="tight">Caution</h6>
                <p>
                  Using a proxy will expose your client secret to the proxy
                  server. If possible, run a local server.
                </p>
                <label htmlFor="proxy_url" hidden>
                  Proxy URL
                </label>
                <input
                  name="proxyUrl"
                  type="url"
                  value={config.proxyUrl}
                  onChange={(event) =>
                    handleConfigChange("proxyUrl", event.target.value)
                  }
                />
              </>
            )}
            <label>
              <input
                name="useBodyCredentials"
                type="checkbox"
                checked={config.useBodyCredentials}
                onChange={(event) =>
                  handleConfigChange("useBodyCredentials", event.target.checked)
                }
              />
              <span
                className="unmarked-tooltip"
                data-tooltip="Instead of using basic authentication, send credentials in the request body."
                data-placement="right"
              >
                Use body credentials
              </span>
            </label>
          </fieldset>
          <input type="submit" className="primary standalone" value="Go" />
        </div>
        <input name="code" type="hidden" value={data.params.code} />
        <input name="clientId" type="hidden" value={data.params.clientId} />
        {data.params.redirectUri && (
          <input
            name="redirectUri"
            type="hidden"
            value={data.params.redirectUri}
          />
        )}
      </Form>
    </article>
  );
}
